untitled1/config/routes.rb
Rails.application.routes.draw do
  get 'page/about'

  get 'page/articles'

  get 'page/blog'

  get 'page/calendar'

  get 'page/contact_us'

  get 'page/home'

  get 'page/login'

  get 'page/newsletter'

  get 'page/products'

  get 'hung/teach'

  get 'hung/speak'

  get 'hung/dig'

  get 'say/hello'
  get 'say/goodbye'
  get 'say/something'

end

untitled1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

untitled1/app/controllers/hung_controller.rb
class HungController < ApplicationController
  def teach
  end

  def speak
  end

  def dig
  end
end

untitled1/app/controllers/page_controller.rb
class PageController < ApplicationController
  def about
  end

  def articles
  end

  def blog
  end

  def calendar
  end

  def contact_us
  end

  def home
  end

  def login
  end

  def newsletter
  end

  def products
  end
end

untitled1/app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @yo="ho ho"
    @now=Time.now
  end
  def goodbye

  end
  def something

  end
end

untitled1/app/helpers/application_helper.rb
module ApplicationHelper
end

untitled1/app/helpers/hung_helper.rb
module HungHelper
end

untitled1/app/helpers/page_helper.rb
module PageHelper
end

untitled1/app/helpers/say_helper.rb
module SayHelper
end

untitled1/app/views/hung/dig.html.erb
<h1>Hung#dig</h1>
<p>Find me in app/views/hung/dig.html.erb</p>

untitled1/app/views/hung/speak.html.erb
<h1>Hung#speak</h1>
<p>Find me in app/views/hung/speak.html.erb</p>

untitled1/app/views/hung/teach.html.erb
<h1>Hung#teach</h1>
<p>Find me in app/views/hung/teach.html.erb</p>

untitled1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Untitled1</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>
<body>
<div id="wrapper"><!-- #wrapper -->

  <header><!-- header -->
    <h1><a href="#">Cowboy Up</a></h1>
    <h2>Where the buffalo roam</h2>
    <%= image_tag "cowboyup.jpg", :size => "940x200", :alt => "cowboy up" %>
    <!--<img src="images/cowboyup.jpg" width="940" height="200" alt="">&lt;!&ndash; header image &ndash;&gt;-->
  </header><!-- end of header -->

  <nav><!-- top nav -->
    <div class="menu">
      <ul>
        <li><a href="#">Home</a></li>
        <li><a href="#">About</a>
          <ul>
            <li><%= link_to "teach Hung",hung_teach_path %></li>
            <li><a href="#">History</a></li>
            <li><a href="">Vision</a></li>
          </ul>
        </li>
        <li><a href="#">Products</a>
          <ul>
            <li><a href="#">Spurs</a></li>
            <li><a href="#">Chaps</a></li>
          </ul>
        </li>
        <li><a href="#">Services</a>
          <ul>
            <li><a href="#">Rodeos</a></li>
            <li><a href="#">Wrangling</a></li>
          </ul>
        </li>
        <li><a href="#">Contact Us</a></li>
      </ul>
    </div>
  </nav><!-- end of top nav -->


  <section id="main"><!-- #main content and sidebar area -->
    <section id="container"><!-- #container -->
      <section id="content"><!-- #content -->

        <%= yield %>
</section><!-- end of #content -->
</section><!-- end of #container -->

<aside id="sidebar"><!-- sidebar -->
  <h3>Things To Do</h3>
  <ul>
    <li><a href="#">Play Games</a></li>
    <li><a href="#">Chat With Friends</a></li>
    <li><a href="#">Swap Stories</a></li>
    <li><a href="#">Sell Stuff</a></li>
    <li><a href="#">Buy Stuff</a></li>
    <li><a href="#">Trade Stuff</a></li>
  </ul>

  <h3>Our Sponsors</h3>
  <%= image_tag "ad125.jpg"%><%= image_tag "ad125.jpg" %> <br/>
  <%= image_tag "ad125.jpg"%><%= image_tag "ad125.jpg" %> <br/><br/>

 <!--<img src="images/ad125.jpg" alt="" /> <img src="images/ad125.jpg" alt="" /><br />
  <img src="images/ad125.jpg" alt="" /> <img src="images/ad125.jpg" alt="" /><br /><br />-->

  <h3>Connect With Us</h3>
  <ul>
    <li><a href="#">Twitter</a></li>
    <li><a href="#">Facebook</a></li>
  </ul>

</aside><!-- end of sidebar -->

</section><!-- end of #main content and sidebar-->

<footer>
  <section id="footer-area">

    <section id="footer-outer-block">
      <aside id="first" class="footer-segment">
        <h3>Blogroll</h3>
        <ul>
          <li><a href="#">one linkylink</a></li>
          <li><a href="#">two linkylinks</a></li>
          <li><a href="#">three linkylinks</a></li>
          <li><a href="#">four linkylinks</a></li>
          <li><a href="#">five linkylinks</a></li>
        </ul>
      </aside><!-- end of #first footer segment -->

      <aside id="second" class="footer-segment">
        <h3>Awesome Stuff</h3>
        <ul>
          <li><a href="#">one linkylink</a></li>
          <li><a href="#">two linkylinks</a></li>
          <li><a href="#">three linkylinks</a></li>
          <li><a href="#">four linkylinks</a></li>
          <li><a href="#">five linkylinks</a></li>
        </ul>
      </aside><!-- end of #second footer segment -->

      <aside id="third" class="footer-segment">
        <h3>Coolness</h3>
        <ul>
          <li><a href="#">one linkylink</a></li>
          <li><a href="#">two linkylinks</a></li>
          <li><a href="#">three linkylinks</a></li>
          <li><a href="#">four linkylinks</a></li>
          <li><a href="#">five linkylinks</a></li>
        </ul>
      </aside><!-- end of #third footer segment -->

      <aside id="fourth" class="footer-segment">
        <h3>Blahdyblah</h3>
        <p>Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum.</p>
      </aside><!-- end of #fourth footer segment -->

    </section><!-- end of #footer-outer-block -->

  </section><!-- end of #footer-area -->
</footer>

</div><!-- #wrapper -->
<!-- Free template created by http://freehtml5templates.com -->
</body>
</html>

untitled1/app/views/page/about.html.erb
<h1>Page#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

untitled1/app/views/page/articles.html.erb
<h1>Page#articles</h1>
<p>Find me in app/views/page/articles.html.erb</p>

untitled1/app/views/page/blog.html.erb
<h1>Page#blog</h1>
<p>Find me in app/views/page/blog.html.erb</p>

untitled1/app/views/page/calendar.html.erb
<h1>Page#calendar</h1>
<p>Find me in app/views/page/calendar.html.erb</p>

untitled1/app/views/page/contact_us.html.erb
<h1>Page#contact_us</h1>
<p>Find me in app/views/page/contact_us.html.erb</p>

untitled1/app/views/page/home.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>

untitled1/app/views/page/login.html.erb
<h1>Page#login</h1>
<p>Find me in app/views/page/login.html.erb</p>

untitled1/app/views/page/newsletter.html.erb
<h1>Page#newsletter</h1>
<p>Find me in app/views/page/newsletter.html.erb</p>

untitled1/app/views/page/products.html.erb
<h1>Page#products</h1>
<p>Find me in app/views/page/products.html.erb</p>

untitled1/app/views/say/goodbye.html.erb
<h1>Goodbye Hung!</h1>

untitled1/app/views/say/hello.html.erb
<h1>Say#hello</h1>
<p>Find me in app/views/say/hello.html.erb</p>
Hello Hung!
<%= 2+2 %>
<% 3.times do %>
<h2>HO</h2>
    <p><%= @now %></p>
    <p><%= @yo %></p>

<% end %>
<br>
<%= link_to "teach Hung",hung_teach_path %>